#!/usr/bin/bash

#start swwww
swww query || swww init

#figure out which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#show the correct wallpapper based on the theme
swww img ~/.config/hypr/hitoi-gotou.jpg --outputs HDMI-A-1
swww img ~/.config/hypr/ryou-yamada.png --outputs DP-1

# if [ $THEMEIS == "dark.css" ]; then
#     swww img ~/.config/hypr/wallpaper-dark.jpg
# else
#     swww img ~/.config/hypr/wallpaper.jpg
# fi
